db:
  dsn: root:123456@tcp(127.0.0.1:3306)/gorum?charset=utf8mb4&parseTime=True&loc=Local
server:
  port: 8081
log:
  level: debug
notification:
  smtp: 
    host: smtp.exmail.qq.com
    port: 465
    username: <username>
    password: <password>
site:
  domain: <your_site_name>
  brand: <logo_text>
  footer: |
    Powered by <a href="https://github.com/tasselsd/gorum">Gorum</a>
    <br />
    <a href="https://beian.miit.gov.cn/">鲁ICP备19064057号-1</a>
