// Code generated by qtc from "common.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/common.qtpl:1
package templates

//line templates/common.qtpl:1
import "github.com/tasselsd/gorum/pkg/session"

//line templates/common.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/common.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/common.qtpl:4
type SitePage interface {
//line templates/common.qtpl:4
	Title() string
//line templates/common.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Css() string
//line templates/common.qtpl:4
	StreamCss(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteCss(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Js() string
//line templates/common.qtpl:4
	StreamJs(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteJs(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Body() string
//line templates/common.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
}

//line templates/common.qtpl:11
type DefaultPage struct {
	Session *session.Session
}

//line templates/common.qtpl:14
func (p *DefaultPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:15
}

//line templates/common.qtpl:15
func (p *DefaultPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:15
	p.StreamTitle(qw422016)
//line templates/common.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:15
}

//line templates/common.qtpl:15
func (p *DefaultPage) Title() string {
//line templates/common.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:15
	p.WriteTitle(qb422016)
//line templates/common.qtpl:15
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:15
	return qs422016
//line templates/common.qtpl:15
}

//line templates/common.qtpl:16
func (p *DefaultPage) StreamCss(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:16
	qw422016.N().S(`<link rel="stylesheet" type="text/css" href="/tpl/jhin/css/animate.css"/>`)
//line templates/common.qtpl:18
}

//line templates/common.qtpl:18
func (p *DefaultPage) WriteCss(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:18
	p.StreamCss(qw422016)
//line templates/common.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:18
}

//line templates/common.qtpl:18
func (p *DefaultPage) Css() string {
//line templates/common.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:18
	p.WriteCss(qb422016)
//line templates/common.qtpl:18
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:18
	return qs422016
//line templates/common.qtpl:18
}

//line templates/common.qtpl:19
func (p *DefaultPage) StreamJs(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:19
	qw422016.N().S(`<script async src="/tpl/jhin/js/mathjax/es5/tex-chtml.js"></script>`)
//line templates/common.qtpl:21
}

//line templates/common.qtpl:21
func (p *DefaultPage) WriteJs(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:21
	p.StreamJs(qw422016)
//line templates/common.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:21
}

//line templates/common.qtpl:21
func (p *DefaultPage) Js() string {
//line templates/common.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:21
	p.WriteJs(qb422016)
//line templates/common.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:21
	return qs422016
//line templates/common.qtpl:21
}

//line templates/common.qtpl:22
func (p *DefaultPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:23
}

//line templates/common.qtpl:23
func (p *DefaultPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:23
	p.StreamBody(qw422016)
//line templates/common.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:23
}

//line templates/common.qtpl:23
func (p *DefaultPage) Body() string {
//line templates/common.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:23
	p.WriteBody(qb422016)
//line templates/common.qtpl:23
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:23
	return qs422016
//line templates/common.qtpl:23
}

//line templates/common.qtpl:24
func StreamHTML(qw422016 *qt422016.Writer, page SitePage) {
//line templates/common.qtpl:24
	qw422016.N().S(`<!DOCTYPE html><html lang="zh-hans"><head><meta name="viewport" content="width=device-width,initial-scale=1" /><meta http-equiv="content-type" content="text/html;charset=utf-8"/>`)
//line templates/common.qtpl:30
	page.StreamCss(qw422016)
//line templates/common.qtpl:31
	page.StreamJs(qw422016)
//line templates/common.qtpl:31
	qw422016.N().S(`<style>body {}h1 {font-size: 22px;color: #69c;}a {text-decoration: none;color: #69c}p {padding: 20px 0;}code {fotn-size: 16px;}footer {font-size: 14px;margin: 10px 0 0 0;}ul,li {padding: 0;margin: 0;}</style><title>`)
//line templates/common.qtpl:42
	page.StreamTitle(qw422016)
//line templates/common.qtpl:42
	qw422016.N().S(`</title></head><body>`)
//line templates/common.qtpl:45
	page.StreamBody(qw422016)
//line templates/common.qtpl:45
	qw422016.N().S(`<footer><a href="https://beian.miit.gov.cn/">鲁ICP备19064057号-1</a></footer></body></html>`)
//line templates/common.qtpl:51
}

//line templates/common.qtpl:51
func WriteHTML(qq422016 qtio422016.Writer, page SitePage) {
//line templates/common.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:51
	StreamHTML(qw422016, page)
//line templates/common.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:51
}

//line templates/common.qtpl:51
func HTML(page SitePage) string {
//line templates/common.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:51
	WriteHTML(qb422016, page)
//line templates/common.qtpl:51
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:51
	return qs422016
//line templates/common.qtpl:51
}
