// Code generated by qtc from "common.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/common.qtpl:1
package templates

//line templates/common.qtpl:1
import "github.com/tasselsd/gorum/pkg/session"

//line templates/common.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/common.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/common.qtpl:4
type SitePage interface {
//line templates/common.qtpl:4
	Title() string
//line templates/common.qtpl:4
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Css() string
//line templates/common.qtpl:4
	StreamCss(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteCss(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Js() string
//line templates/common.qtpl:4
	StreamJs(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteJs(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
	Body() string
//line templates/common.qtpl:4
	StreamBody(qw422016 *qt422016.Writer)
//line templates/common.qtpl:4
	WriteBody(qq422016 qtio422016.Writer)
//line templates/common.qtpl:4
}

//line templates/common.qtpl:12
type DefaultPage struct {
	Session *session.Session
}

type ErrorPage struct {
	DefaultPage
	StatusCode int
	Detail     string
}

type SuccessPage struct {
	DefaultPage
	Detail string
}

//line templates/common.qtpl:28
func (p *DefaultPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:29
}

//line templates/common.qtpl:29
func (p *DefaultPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:29
	p.StreamTitle(qw422016)
//line templates/common.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:29
}

//line templates/common.qtpl:29
func (p *DefaultPage) Title() string {
//line templates/common.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:29
	p.WriteTitle(qb422016)
//line templates/common.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:29
	return qs422016
//line templates/common.qtpl:29
}

//line templates/common.qtpl:31
func (p *DefaultPage) StreamCss(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:32
}

//line templates/common.qtpl:32
func (p *DefaultPage) WriteCss(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:32
	p.StreamCss(qw422016)
//line templates/common.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:32
}

//line templates/common.qtpl:32
func (p *DefaultPage) Css() string {
//line templates/common.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:32
	p.WriteCss(qb422016)
//line templates/common.qtpl:32
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:32
	return qs422016
//line templates/common.qtpl:32
}

//line templates/common.qtpl:34
func (p *DefaultPage) StreamJs(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:35
}

//line templates/common.qtpl:35
func (p *DefaultPage) WriteJs(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:35
	p.StreamJs(qw422016)
//line templates/common.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:35
}

//line templates/common.qtpl:35
func (p *DefaultPage) Js() string {
//line templates/common.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:35
	p.WriteJs(qb422016)
//line templates/common.qtpl:35
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:35
	return qs422016
//line templates/common.qtpl:35
}

//line templates/common.qtpl:37
func (p *DefaultPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:38
}

//line templates/common.qtpl:38
func (p *DefaultPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:38
	p.StreamBody(qw422016)
//line templates/common.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:38
}

//line templates/common.qtpl:38
func (p *DefaultPage) Body() string {
//line templates/common.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:38
	p.WriteBody(qb422016)
//line templates/common.qtpl:38
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:38
	return qs422016
//line templates/common.qtpl:38
}

//line templates/common.qtpl:40
func StreamHTML(qw422016 *qt422016.Writer, page SitePage) {
//line templates/common.qtpl:40
	qw422016.N().S(`<!DOCTYPE html><html lang="zh-hans"><head><meta name="viewport" content="width=device-width,initial-scale=1" /><meta http-equiv="content-type" content="text/html;charset=utf-8"/>`)
//line templates/common.qtpl:46
	page.StreamCss(qw422016)
//line templates/common.qtpl:47
	page.StreamJs(qw422016)
//line templates/common.qtpl:47
	qw422016.N().S(`<title>`)
//line templates/common.qtpl:48
	page.StreamTitle(qw422016)
//line templates/common.qtpl:48
	qw422016.N().S(`</title><style>body {}h1 {font-size: 22px;color: #69c;}a {text-decoration: none;color: #69c}p {padding: 20px 0;}form input {display: block;margin: 5px 0}code {fotn-size: 16px;}footer {font-size: 14px;margin: 10px 0 0 0;}ul,li {padding: 0;margin: 0;}.error-nav {margin: 10px 0 0 0}.avatar {width: 32px;height: 32px;}</style></head><body>`)
//line templates/common.qtpl:65
	page.StreamBody(qw422016)
//line templates/common.qtpl:65
	qw422016.N().S(`<footer><a href="https://beian.miit.gov.cn/">鲁ICP备19064057号-1</a></footer></body></html>`)
//line templates/common.qtpl:71
}

//line templates/common.qtpl:71
func WriteHTML(qq422016 qtio422016.Writer, page SitePage) {
//line templates/common.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:71
	StreamHTML(qw422016, page)
//line templates/common.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:71
}

//line templates/common.qtpl:71
func HTML(page SitePage) string {
//line templates/common.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:71
	WriteHTML(qb422016, page)
//line templates/common.qtpl:71
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:71
	return qs422016
//line templates/common.qtpl:71
}

//line templates/common.qtpl:73
func (p *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:73
	qw422016.N().S(`<div class="error-tips"><div class="status-code">`)
//line templates/common.qtpl:75
	qw422016.N().D(p.StatusCode)
//line templates/common.qtpl:75
	qw422016.N().S(`</div><div class="error-detail">`)
//line templates/common.qtpl:76
	qw422016.E().S(p.Detail)
//line templates/common.qtpl:76
	qw422016.N().S(`</div></div><div class="error-nav"><ul><li><a href="javascript:history.go(-1);">返回上一步</a></ul></a>`)
//line templates/common.qtpl:83
}

//line templates/common.qtpl:83
func (p *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:83
	p.StreamBody(qw422016)
//line templates/common.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:83
}

//line templates/common.qtpl:83
func (p *ErrorPage) Body() string {
//line templates/common.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:83
	p.WriteBody(qb422016)
//line templates/common.qtpl:83
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:83
	return qs422016
//line templates/common.qtpl:83
}

//line templates/common.qtpl:84
func (p *ErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:84
	qw422016.N().S(`出现一个错误`)
//line templates/common.qtpl:86
}

//line templates/common.qtpl:86
func (p *ErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:86
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:86
	p.StreamTitle(qw422016)
//line templates/common.qtpl:86
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:86
}

//line templates/common.qtpl:86
func (p *ErrorPage) Title() string {
//line templates/common.qtpl:86
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:86
	p.WriteTitle(qb422016)
//line templates/common.qtpl:86
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:86
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:86
	return qs422016
//line templates/common.qtpl:86
}

//line templates/common.qtpl:88
func (p *SuccessPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:88
	qw422016.N().S(`<div class="success-tips"><div class="status-code">200</div><div class="error-detail">`)
//line templates/common.qtpl:91
	qw422016.E().S(p.Detail)
//line templates/common.qtpl:91
	qw422016.N().S(`</div></div><div class="success-nav"><ul><li><a href="javascript:history.go(-1);">返回上一步</a></ul></a>`)
//line templates/common.qtpl:98
}

//line templates/common.qtpl:98
func (p *SuccessPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:98
	p.StreamBody(qw422016)
//line templates/common.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:98
}

//line templates/common.qtpl:98
func (p *SuccessPage) Body() string {
//line templates/common.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:98
	p.WriteBody(qb422016)
//line templates/common.qtpl:98
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:98
	return qs422016
//line templates/common.qtpl:98
}

//line templates/common.qtpl:99
func (p *SuccessPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/common.qtpl:99
	qw422016.N().S(`操作成功`)
//line templates/common.qtpl:101
}

//line templates/common.qtpl:101
func (p *SuccessPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/common.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/common.qtpl:101
	p.StreamTitle(qw422016)
//line templates/common.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line templates/common.qtpl:101
}

//line templates/common.qtpl:101
func (p *SuccessPage) Title() string {
//line templates/common.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/common.qtpl:101
	p.WriteTitle(qb422016)
//line templates/common.qtpl:101
	qs422016 := string(qb422016.B)
//line templates/common.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/common.qtpl:101
	return qs422016
//line templates/common.qtpl:101
}
