// Code generated by qtc from "discuss.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/discuss.qtpl:2
package templates

//line templates/discuss.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/discuss.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/discuss.qtpl:2
func StreamDiscussPage(qw422016 *qt422016.Writer, root interface{}) {
//line templates/discuss.qtpl:3
}

//line templates/discuss.qtpl:3
func WriteDiscussPage(qq422016 qtio422016.Writer, root interface{}) {
//line templates/discuss.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/discuss.qtpl:3
	StreamDiscussPage(qw422016, root)
//line templates/discuss.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line templates/discuss.qtpl:3
}

//line templates/discuss.qtpl:3
func DiscussPage(root interface{}) string {
//line templates/discuss.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/discuss.qtpl:3
	WriteDiscussPage(qb422016, root)
//line templates/discuss.qtpl:3
	qs422016 := string(qb422016.B)
//line templates/discuss.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/discuss.qtpl:3
	return qs422016
//line templates/discuss.qtpl:3
}
