// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:2
package templates

//line templates/index.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:3
type IndexPage struct {
	DefaultPage
	Recommends []Recommend
}
type Recommend struct {
	DiscussID    uint
	ShortSha1    string
	DiscussName  string
	Initiator    string
	InitiatorUID uint
}

//line templates/index.qtpl:15
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:15
	qw422016.N().S(`<ul>`)
//line templates/index.qtpl:17
	for _, r := range p.Recommends {
//line templates/index.qtpl:17
		qw422016.N().S(`<li><a href="/d/`)
//line templates/index.qtpl:18
		qw422016.E().S(r.ShortSha1)
//line templates/index.qtpl:18
		qw422016.N().S(`">`)
//line templates/index.qtpl:18
		qw422016.E().S(r.DiscussName)
//line templates/index.qtpl:18
		qw422016.N().S(`</a></li>`)
//line templates/index.qtpl:19
	}
//line templates/index.qtpl:19
	qw422016.N().S(`</ul>`)
//line templates/index.qtpl:21
}

//line templates/index.qtpl:21
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:21
	p.StreamBody(qw422016)
//line templates/index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:21
}

//line templates/index.qtpl:21
func (p *IndexPage) Body() string {
//line templates/index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:21
	p.WriteBody(qb422016)
//line templates/index.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:21
	return qs422016
//line templates/index.qtpl:21
}
