// Code generated by qtc from "signup.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/signup.qtpl:3
package templates

//line templates/signup.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/signup.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/signup.qtpl:4
type SignupPage struct {
	DefaultPage
}
type SigninPage struct {
	DefaultPage
}
type ActivationPage struct {
	DefaultPage
}

//line templates/signup.qtpl:15
func (p *SignupPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:15
	qw422016.N().S(`<div class="sign-area"><form method="post" action="/signup"><input type="email" name="email" /><input type="text" name="name" /><input type="password" name="password" /><input type="submit" value="注册" /></form><div class="sign-links"><ul><li><a href="/signin">登录</a></li></ul></div></div>`)
//line templates/signup.qtpl:29
}

//line templates/signup.qtpl:29
func (p *SignupPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:29
	p.StreamBody(qw422016)
//line templates/signup.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:29
}

//line templates/signup.qtpl:29
func (p *SignupPage) Body() string {
//line templates/signup.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:29
	p.WriteBody(qb422016)
//line templates/signup.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:29
	return qs422016
//line templates/signup.qtpl:29
}

//line templates/signup.qtpl:30
func (p *SignupPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:30
	qw422016.N().S(`注册`)
//line templates/signup.qtpl:32
}

//line templates/signup.qtpl:32
func (p *SignupPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:32
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:32
}

//line templates/signup.qtpl:32
func (p *SignupPage) Title() string {
//line templates/signup.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:32
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:32
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:32
	return qs422016
//line templates/signup.qtpl:32
}

//line templates/signup.qtpl:34
func (p *SigninPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:34
	qw422016.N().S(`<div class="sign-area"><form method="post" action="/signin"><input type="text" name="signin" /><input type="password" name="password" /><input type="submit" value="登录" /></form><div class="sign-links"><ul><li><a href="/signup">注册帐号</a></li></ul></div></div>`)
//line templates/signup.qtpl:47
}

//line templates/signup.qtpl:47
func (p *SigninPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:47
	p.StreamBody(qw422016)
//line templates/signup.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:47
}

//line templates/signup.qtpl:47
func (p *SigninPage) Body() string {
//line templates/signup.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:47
	p.WriteBody(qb422016)
//line templates/signup.qtpl:47
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:47
	return qs422016
//line templates/signup.qtpl:47
}

//line templates/signup.qtpl:48
func (p *SigninPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:48
	qw422016.N().S(`登录`)
//line templates/signup.qtpl:50
}

//line templates/signup.qtpl:50
func (p *SigninPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:50
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:50
}

//line templates/signup.qtpl:50
func (p *SigninPage) Title() string {
//line templates/signup.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:50
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:50
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:50
	return qs422016
//line templates/signup.qtpl:50
}

//line templates/signup.qtpl:52
func (p *ActivationPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:52
	qw422016.N().S(`<div class="activation-tips">你的帐号已登记注册！但此刻还未激活！<br /><br />注册时填写邮箱的收件箱似乎已经收到了一封激活邮件，请点击链接激活它</div><div class="error-nav"><ul><li><a href="javascript:history.go(-1);">返回上一步</a></ul></a></div>`)
//line templates/signup.qtpl:62
}

//line templates/signup.qtpl:62
func (p *ActivationPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:62
	p.StreamBody(qw422016)
//line templates/signup.qtpl:62
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:62
}

//line templates/signup.qtpl:62
func (p *ActivationPage) Body() string {
//line templates/signup.qtpl:62
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:62
	p.WriteBody(qb422016)
//line templates/signup.qtpl:62
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:62
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:62
	return qs422016
//line templates/signup.qtpl:62
}

//line templates/signup.qtpl:63
func (p *ActivationPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:63
	qw422016.N().S(`激活帐号`)
//line templates/signup.qtpl:65
}

//line templates/signup.qtpl:65
func (p *ActivationPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:65
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:65
}

//line templates/signup.qtpl:65
func (p *ActivationPage) Title() string {
//line templates/signup.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:65
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:65
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:65
	return qs422016
//line templates/signup.qtpl:65
}
