// Code generated by qtc from "signup.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/signup.qtpl:1
package templates

//line templates/signup.qtpl:1
import "github.com/tasselsd/gorum/pkg/core"

//line templates/signup.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/signup.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/signup.qtpl:5
type SignupPage struct {
	DefaultPage
}
type SigninPage struct {
	DefaultPage
}
type ActivationPage struct {
	DefaultPage
}
type ActivatedPage struct {
	DefaultPage
}
type RequestResetPasswordPage struct {
	DefaultPage
}
type ResetPasswordPage struct {
	DefaultPage
	User  *core.User
	Token string
}

//line templates/signup.qtpl:27
func (p *SignupPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:27
	qw422016.N().S(`<div class="sign-area"><form method="post" action="/signup"><input type="email" name="email" /><input type="text" name="name" /><input type="password" name="password" /><input type="submit" value="注册" /></form><div class="sign-links"><ul><li><a href="/signin">登录</a></li></ul></div></div>`)
//line templates/signup.qtpl:41
}

//line templates/signup.qtpl:41
func (p *SignupPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:41
	p.StreamBody(qw422016)
//line templates/signup.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:41
}

//line templates/signup.qtpl:41
func (p *SignupPage) Body() string {
//line templates/signup.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:41
	p.WriteBody(qb422016)
//line templates/signup.qtpl:41
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:41
	return qs422016
//line templates/signup.qtpl:41
}

//line templates/signup.qtpl:42
func (p *SignupPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:42
	qw422016.N().S(`注册`)
//line templates/signup.qtpl:44
}

//line templates/signup.qtpl:44
func (p *SignupPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:44
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:44
}

//line templates/signup.qtpl:44
func (p *SignupPage) Title() string {
//line templates/signup.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:44
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:44
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:44
	return qs422016
//line templates/signup.qtpl:44
}

//line templates/signup.qtpl:46
func (p *SigninPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:46
	qw422016.N().S(`<div class="sign-area"><form method="post" action="/signin"><input type="text" name="signin" /><input type="password" name="password" /><input type="submit" value="登录" /></form><div class="sign-links"><ul><li><a href="/signup">注册帐号</a></li><li><a href="/reset-password-request">重置密码</a></li></ul></div></div>`)
//line templates/signup.qtpl:60
}

//line templates/signup.qtpl:60
func (p *SigninPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:60
	p.StreamBody(qw422016)
//line templates/signup.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:60
}

//line templates/signup.qtpl:60
func (p *SigninPage) Body() string {
//line templates/signup.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:60
	p.WriteBody(qb422016)
//line templates/signup.qtpl:60
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:60
	return qs422016
//line templates/signup.qtpl:60
}

//line templates/signup.qtpl:61
func (p *SigninPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:61
	qw422016.N().S(`登录`)
//line templates/signup.qtpl:63
}

//line templates/signup.qtpl:63
func (p *SigninPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:63
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:63
}

//line templates/signup.qtpl:63
func (p *SigninPage) Title() string {
//line templates/signup.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:63
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:63
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:63
	return qs422016
//line templates/signup.qtpl:63
}

//line templates/signup.qtpl:65
func (p *RequestResetPasswordPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:65
	qw422016.N().S(`<div class="sign-area"><form method="post" action="/reset-password-request"><input type="email" name="email" /><input type="submit" value="提交申请" /></form><div class="sign-links"><ul><li><a href="/signup">注册帐号</a></li><li><a href="/signin">登录</a></li></ul></div></div>`)
//line templates/signup.qtpl:78
}

//line templates/signup.qtpl:78
func (p *RequestResetPasswordPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:78
	p.StreamBody(qw422016)
//line templates/signup.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:78
}

//line templates/signup.qtpl:78
func (p *RequestResetPasswordPage) Body() string {
//line templates/signup.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:78
	p.WriteBody(qb422016)
//line templates/signup.qtpl:78
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:78
	return qs422016
//line templates/signup.qtpl:78
}

//line templates/signup.qtpl:79
func (p *RequestResetPasswordPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:79
	qw422016.N().S(`申请重置密码`)
//line templates/signup.qtpl:81
}

//line templates/signup.qtpl:81
func (p *RequestResetPasswordPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:81
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:81
}

//line templates/signup.qtpl:81
func (p *RequestResetPasswordPage) Title() string {
//line templates/signup.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:81
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:81
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:81
	return qs422016
//line templates/signup.qtpl:81
}

//line templates/signup.qtpl:83
func (p *ResetPasswordPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:83
	qw422016.N().S(`<div class="sign-area"><div class="current-user">`)
//line templates/signup.qtpl:85
	qw422016.E().S(p.User.Name)
//line templates/signup.qtpl:85
	qw422016.N().S(`</div><form method="post" action="/reset-password"><input type="password" name="password" /><input type="password" name="token" value="`)
//line templates/signup.qtpl:88
	qw422016.E().S(p.Token)
//line templates/signup.qtpl:88
	qw422016.N().S(`" style="display: none" /><input type="submit" value="重置密码" /></form><div class="sign-links"><ul><li><a href="/signup">注册帐号</a></li><li><a href="/signin">登录</a></li></ul></div></div>`)
//line templates/signup.qtpl:98
}

//line templates/signup.qtpl:98
func (p *ResetPasswordPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:98
	p.StreamBody(qw422016)
//line templates/signup.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:98
}

//line templates/signup.qtpl:98
func (p *ResetPasswordPage) Body() string {
//line templates/signup.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:98
	p.WriteBody(qb422016)
//line templates/signup.qtpl:98
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:98
	return qs422016
//line templates/signup.qtpl:98
}

//line templates/signup.qtpl:99
func (p *ResetPasswordPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:99
	qw422016.N().S(`重置密码`)
//line templates/signup.qtpl:101
}

//line templates/signup.qtpl:101
func (p *ResetPasswordPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:101
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:101
}

//line templates/signup.qtpl:101
func (p *ResetPasswordPage) Title() string {
//line templates/signup.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:101
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:101
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:101
	return qs422016
//line templates/signup.qtpl:101
}

//line templates/signup.qtpl:103
func (p *ActivationPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:103
	qw422016.N().S(`<div class="activation-tips">你的帐号已登记注册！但此刻还未激活！<br /><br />注册时填写邮箱的收件箱似乎已经收到了一封激活邮件，请点击链接激活它</div><div class="error-nav"><ul><li><a href="javascript:history.go(-1);">返回上一步</a></ul></a></div>`)
//line templates/signup.qtpl:113
}

//line templates/signup.qtpl:113
func (p *ActivationPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:113
	p.StreamBody(qw422016)
//line templates/signup.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:113
}

//line templates/signup.qtpl:113
func (p *ActivationPage) Body() string {
//line templates/signup.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:113
	p.WriteBody(qb422016)
//line templates/signup.qtpl:113
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:113
	return qs422016
//line templates/signup.qtpl:113
}

//line templates/signup.qtpl:114
func (p *ActivationPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:114
	qw422016.N().S(`激活帐号`)
//line templates/signup.qtpl:116
}

//line templates/signup.qtpl:116
func (p *ActivationPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:116
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:116
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:116
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:116
}

//line templates/signup.qtpl:116
func (p *ActivationPage) Title() string {
//line templates/signup.qtpl:116
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:116
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:116
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:116
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:116
	return qs422016
//line templates/signup.qtpl:116
}

//line templates/signup.qtpl:118
func (p *ActivatedPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:118
	qw422016.N().S(`<div class="activated-tips">激活成功，正在<a href="/">跳转首页</a>...</div><script>setTimeout(()=>window.location.href="/", 1000)</script>`)
//line templates/signup.qtpl:125
}

//line templates/signup.qtpl:125
func (p *ActivatedPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:125
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:125
	p.StreamBody(qw422016)
//line templates/signup.qtpl:125
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:125
}

//line templates/signup.qtpl:125
func (p *ActivatedPage) Body() string {
//line templates/signup.qtpl:125
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:125
	p.WriteBody(qb422016)
//line templates/signup.qtpl:125
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:125
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:125
	return qs422016
//line templates/signup.qtpl:125
}

//line templates/signup.qtpl:126
func (p *ActivatedPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/signup.qtpl:126
	qw422016.N().S(`激活成功`)
//line templates/signup.qtpl:128
}

//line templates/signup.qtpl:128
func (p *ActivatedPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/signup.qtpl:128
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/signup.qtpl:128
	p.StreamTitle(qw422016)
//line templates/signup.qtpl:128
	qt422016.ReleaseWriter(qw422016)
//line templates/signup.qtpl:128
}

//line templates/signup.qtpl:128
func (p *ActivatedPage) Title() string {
//line templates/signup.qtpl:128
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/signup.qtpl:128
	p.WriteTitle(qb422016)
//line templates/signup.qtpl:128
	qs422016 := string(qb422016.B)
//line templates/signup.qtpl:128
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/signup.qtpl:128
	return qs422016
//line templates/signup.qtpl:128
}
